services:
  - type: worker
    name: sk-instagram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_OWNER_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.10
